### ISSUE TITLE
Problem with dark-hybrid-theme

### ISSUE THREAD

**Issue by melbv** [iganeshk/standardnotes-extensions#25]
Hi there
Many thanks for making the SN extensions available. 
I was trying to build the repo but got the following error for the dark-hybrid theme:
Would you know where this would come from? as it break the constitution of the repo, i cannot at the moment access the /extensions webpage!
Thanks in advance
Mel

```
Traceback (most recent call last):
  File "build_repo.py", line 283, in <module>
    main()
  File "build_repo.py", line 268, in main
    parse_extensions(base_dir, base_url, ghub_session)
  File "build_repo.py", line 137, in parse_extensions
    ext_yaml = yaml.load(extyaml, Loader=yaml.FullLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
```

**Comment by mrichtsfeld** [comment]
Hi @melbv,
I had the same issue about a week ago. There is a typo in that file, a space at the very beginning before the "---". I removed that space and it worked again. I have also created a pull request for this issue: https://github.com/iganeshk/standardnotes-extensions/pull/24

Hope that helps.

**Comment by melbv** [comment]
Thanks @mrichtsfeld - it did the trick indeed!
